"""Initial tables

Revision ID: ae9d34abb4b1
Revises: 
Create Date: 2026-03-25 19:58:57.990888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9d34abb4b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('registration_no', sa.String(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('registration_no')
    )
    op.create_table('parkings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flagged_cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('subscription_close_to_expiration', 'subscription_expired', 'car_in_wrong_parking', 'no_subscription', name='flagtype'), nullable=False),
    sa.Column('car_registration_no', sa.String(), nullable=False),
    sa.Column('parking_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_image_url', sa.String(), nullable=True),
    sa.Column('requires_human_verification', sa.Boolean(), nullable=False),
    sa.Column('verified_by_human', sa.Boolean(), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_registration_no'], ['cars.registration_no'], ),
    sa.ForeignKeyConstraint(['parking_id'], ['parkings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flag_car_reg', 'flagged_cars', ['car_registration_no'], unique=False)
    op.create_index('idx_flag_parking', 'flagged_cars', ['parking_id'], unique=False)
    op.create_index('idx_flag_req_human', 'flagged_cars', ['requires_human_verification'], unique=False)
    op.create_index('idx_flag_type', 'flagged_cars', ['type'], unique=False)
    op.create_index('idx_flag_verified', 'flagged_cars', ['verified_by_human'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_registration_no', sa.String(), nullable=False),
    sa.Column('parking_id', sa.Integer(), nullable=False),
    sa.Column('begin_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_registration_no'], ['cars.registration_no'], ),
    sa.ForeignKeyConstraint(['parking_id'], ['parkings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_registration_no', 'parking_id', 'begin_date', name='uix_car_parking_date')
    )
    op.create_index('idx_sub_car_reg', 'subscriptions', ['car_registration_no'], unique=False)
    op.create_index('idx_sub_parking', 'subscriptions', ['parking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sub_parking', table_name='subscriptions')
    op.drop_index('idx_sub_car_reg', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_flag_verified', table_name='flagged_cars')
    op.drop_index('idx_flag_type', table_name='flagged_cars')
    op.drop_index('idx_flag_req_human', table_name='flagged_cars')
    op.drop_index('idx_flag_parking', table_name='flagged_cars')
    op.drop_index('idx_flag_car_reg', table_name='flagged_cars')
    op.drop_table('flagged_cars')
    op.drop_table('users')
    op.drop_table('parkings')
    op.drop_table('cars')
    # ### end Alembic commands ###
